server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: login-service
  datasource:
    url: jdbc:mysql://10.0.0.66:3306/db_user?characterEncoding=utf8&useSSL=false
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123456
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    sql-parser-cache: true
    db-config:
      id-type: id_worker_str
      field-strategy: not_null
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
logging.level.org.springframework.boot.autoconfigure: ERROR
