server:
  port: 9003
spring:
  cloud:
    config:
      server:
        default-application-name: config-server
        git:
          uri: https://github.com/wangxiaoxiaozuo/spring-cloud-config/
          username: wangxiaoxiaozuo
          password: wj@962464
          search-paths: {application}/{application}-config
      label: master
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/